"use client";

import React, { useState } from "react";
import { 
  Terminal, 
  Sparkles, 
  Send, 
  Cpu, 
  DollarSign, 
  Clock, 
  Layers, 
  Sliders, 
  Database,
  Code2,
  CheckCircle2,
  Loader2,
  Copy,
  Check
} from "lucide-react";
import { simulateAdaptiveRouting } from "@/lib/mockData";

export default function PlaygroundPage() {
  const [systemPrompt, setSystemPrompt] = useState(
    "You are a helpful software engineering assistant with high precision and concise code explanations."
  );
  const [userPrompt, setUserPrompt] = useState(
    "Design a distributed consensus mechanism using Raft, handling leader election partitions."
  );
  const [routingPolicy, setRoutingPolicy] = useState<"Adaptive-Cost" | "Latency-First" | "Quality-First">("Adaptive-Cost");
  const [isExecuting, setIsExecuting] = useState(false);
  const [activeTab, setActiveTab] = useState<"response" | "json">("response");
  const [copied, setCopied] = useState(false);

  const [decision, setDecision] = useState(() => simulateAdaptiveRouting(userPrompt));
  const [simulatedResponse, setSimulatedResponse] = useState(
    "In Raft consensus, network partitions are resolved through randomized election timers and quorum verification (N/2 + 1). If a leader is partitioned with a minority of nodes, it cannot commit log entries because it fails to receive majority heartbeats. When the partition heals, the term counter from the majority cluster forces the stale leader to step down immediately..."
  );

  const handleExecute = () => {
    if (!userPrompt.trim()) return;
    setIsExecuting(true);

    setTimeout(() => {
      const res = simulateAdaptiveRouting(userPrompt);
      // Adjust based on policy
      if (routingPolicy === "Latency-First" && res.selectedTier !== "fast") {
        res.selectedTier = "fast";
        res.modelName = "Fast Model (Llama 3.1 8B Instant)";
        res.reason = "Latency-First policy forced fastest model tier (<150ms).";
        res.latencyMs = 114;
        res.cost = 0.0008;
      } else if (routingPolicy === "Quality-First" && res.selectedTier !== "powerful") {
        res.selectedTier = "powerful";
        res.modelName = "Powerful Model (Claude 3.7 Sonnet)";
        res.reason = "Quality-First policy escalated to maximum frontier reasoning model.";
        res.latencyMs = 820;
        res.cost = 0.019;
      }

      setDecision(res);

      if (res.cacheHit) {
        setSimulatedResponse(
          `[INSTANT VECTOR CACHE HIT • 14ms]\n\nCached response retrieved for semantic match:\n${userPrompt}\n\nHere is the verified response directly from local embedding memory.`
        );
      } else {
        setSimulatedResponse(
          `Here is the architectural response generated by ${res.modelName}:\n\n1. Overview & Constraints:\nBased on your prompt, we evaluate the requirements through a structured design.\n\n2. Implementation Details:\n- Term & Heartbeat: Configured at 150-300ms intervals to prevent split votes.\n- Commit Index: Advanced only upon acknowledgement from majority nodes.\n- State Machine Safety: Guaranteed by term monotonicity.\n\n[Tokens billed: ${res.tokens.total} • Latency: ${res.latencyMs}ms • Cost: $${res.cost.toFixed(4)}]`
        );
      }

      setIsExecuting(false);
    }, 700);
  };

  const copyJson = () => {
    navigator.clipboard.writeText(JSON.stringify(decision, null, 2));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-zinc-800">
        <div>
          <div className="flex items-center gap-3">
            <h1 className="text-xl sm:text-2xl font-bold tracking-tight text-white font-mono">
              Gateway Playground
            </h1>
            <span className="px-2.5 py-0.5 rounded-full bg-[#00f0ff]/10 text-[#00f0ff] border border-[#00f0ff]/20 text-xs font-mono font-medium">
              Live Interactive Sandbox
            </span>
          </div>
          <p className="text-xs sm:text-sm text-zinc-400 mt-1">
            Test custom prompts, configure routing policies, and inspect raw telemetry headers in real time.
          </p>
        </div>

        {/* Policy Selector */}
        <div className="flex items-center gap-2">
          <span className="text-xs font-mono text-zinc-400 hidden sm:inline">Policy:</span>
          <div className="flex items-center p-1 rounded-xl bg-zinc-900 border border-zinc-800 text-xs font-mono">
            {(["Adaptive-Cost", "Latency-First", "Quality-First"] as const).map((p) => (
              <button
                key={p}
                onClick={() => setRoutingPolicy(p)}
                className={`px-3 py-1.5 rounded-lg transition-all ${
                  routingPolicy === p
                    ? "bg-[#00f0ff]/15 text-[#00f0ff] border border-[#00f0ff]/30 font-semibold"
                    : "text-zinc-400 hover:text-zinc-200"
                }`}
              >
                {p}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Grid: 2 Columns */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        {/* Left Column: Prompts & Execution Controls */}
        <div className="lg:col-span-6 space-y-4">
          {/* System Prompt Box */}
          <div className="rounded-2xl border border-zinc-800 bg-zinc-900/40 p-4">
            <div className="flex items-center justify-between mb-2">
              <span className="text-[10px] font-mono uppercase tracking-wider text-zinc-400">
                System Prompt (Optional)
              </span>
              <span className="text-[10px] font-mono text-zinc-500">role: system</span>
            </div>
            <textarea
              rows={2}
              value={systemPrompt}
              onChange={(e) => setSystemPrompt(e.target.value)}
              className="w-full rounded-xl border border-zinc-700/80 bg-zinc-950 p-3 font-mono text-xs text-zinc-200 placeholder-zinc-500 focus:outline-none focus:border-[#00f0ff] transition-all resize-none"
            />
          </div>

          {/* User Prompt Box */}
          <div className="rounded-2xl border border-zinc-800 bg-zinc-900/40 p-4">
            <div className="flex items-center justify-between mb-2">
              <span className="text-[10px] font-mono uppercase tracking-wider text-[#00f0ff] font-semibold">
                User Inbound Prompt
              </span>
              <span className="text-[10px] font-mono text-zinc-500">{userPrompt.length} chars</span>
            </div>
            <textarea
              rows={6}
              value={userPrompt}
              onChange={(e) => setUserPrompt(e.target.value)}
              placeholder="Enter your prompt here..."
              className="w-full rounded-xl border border-zinc-700/80 bg-zinc-950 p-3.5 font-mono text-xs text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-[#00f0ff] focus:ring-1 focus:ring-[#00f0ff] transition-all resize-none"
            />

            {/* Quick Templates */}
            <div className="mt-3">
              <span className="text-[10px] font-mono uppercase text-zinc-400 block mb-1.5">
                Quick Load Presets:
              </span>
              <div className="flex flex-wrap gap-1.5">
                {[
                  "Design a distributed consensus mechanism using Raft",
                  "What is TCP protocol 3-way handshake?",
                  "Write a Python script to parse CSV files and compute standard deviation",
                  "Prove that the square root of 2 is irrational using contradiction",
                ].map((txt, idx) => (
                  <button
                    key={idx}
                    onClick={() => {
                      setUserPrompt(txt);
                    }}
                    className="text-[10px] font-mono px-2 py-1 rounded bg-zinc-800/80 hover:bg-zinc-700 text-zinc-300 border border-zinc-700/50 truncate max-w-xs text-left"
                  >
                    {txt}
                  </button>
                ))}
              </div>
            </div>

            {/* Execute Button */}
            <div className="mt-4 pt-3 border-t border-zinc-800 flex items-center justify-between">
              <span className="text-xs font-mono text-zinc-400">
                Endpoint: <code className="text-zinc-300">/v1/chat/completions</code>
              </span>
              <button
                onClick={handleExecute}
                disabled={isExecuting}
                className="inline-flex items-center gap-2 rounded-xl bg-[#00f0ff] hover:bg-[#38bdf8] text-zinc-950 font-bold px-5 py-2.5 text-xs font-mono tracking-wide transition-all shadow-[0_0_20px_-3px_rgba(0,240,255,0.4)] disabled:opacity-50"
              >
                {isExecuting ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" />
                    <span>Routing & Invoking...</span>
                  </>
                ) : (
                  <>
                    <span>Route & Execute</span>
                    <Send className="h-3.5 w-3.5" />
                  </>
                )}
              </button>
            </div>
          </div>
        </div>

        {/* Right Column: Routing Diagnostics & Response Preview */}
        <div className="lg:col-span-6 space-y-4">
          {/* Decision Summary Card */}
          <div className="rounded-2xl border border-zinc-800 bg-[#0c0e14] p-5 shadow-xl relative">
            <div className="flex items-center justify-between pb-3 border-b border-zinc-800">
              <div className="flex items-center gap-2">
                <Sparkles className="h-4 w-4 text-[#00f0ff]" />
                <span className="text-xs font-mono font-bold text-zinc-100 uppercase">
                  Adaptive Router Evaluation
                </span>
              </div>
              <span className="text-xs font-mono px-2 py-0.5 rounded bg-zinc-900 border border-zinc-800 text-[#00f0ff]">
                Confidence: {decision.confidence}%
              </span>
            </div>

            {/* Diagnostics Stats */}
            <div className="grid grid-cols-3 gap-2 py-3 border-b border-zinc-800/80 text-center font-mono">
              <div className="p-2 rounded bg-zinc-950 border border-zinc-800/80">
                <span className="text-[10px] text-zinc-400 uppercase block">Selected Tier</span>
                <span className="text-xs font-bold text-[#00f0ff] uppercase">{decision.selectedTier}</span>
              </div>
              <div className="p-2 rounded bg-zinc-950 border border-zinc-800/80">
                <span className="text-[10px] text-zinc-400 uppercase block">Total Latency</span>
                <span className="text-xs font-bold text-zinc-200">{decision.latencyMs}ms</span>
              </div>
              <div className="p-2 rounded bg-zinc-950 border border-zinc-800/80">
                <span className="text-[10px] text-zinc-400 uppercase block">Estimated Cost</span>
                <span className="text-xs font-bold text-emerald-400">${decision.cost.toFixed(4)}</span>
              </div>
            </div>

            <div className="py-3 font-mono text-xs">
              <div className="flex justify-between text-zinc-400 mb-1">
                <span>Model Target:</span>
                <span className="text-zinc-100 font-semibold">{decision.modelName}</span>
              </div>
              <div className="flex justify-between text-zinc-400">
                <span>Routing Reason:</span>
                <span className="text-zinc-300 text-right max-w-xs italic text-[11px]">
                  &ldquo;{decision.reason}&rdquo;
                </span>
              </div>
            </div>
          </div>

          {/* Response or JSON Inspector */}
          <div className="rounded-2xl border border-zinc-800 bg-zinc-900/40 p-5 shadow-sm">
            <div className="flex items-center justify-between pb-3 border-b border-zinc-800 text-xs font-mono">
              <div className="flex items-center gap-2">
                <button
                  onClick={() => setActiveTab("response")}
                  className={`px-3 py-1 rounded-lg transition-all ${
                    activeTab === "response"
                      ? "bg-zinc-800 text-zinc-100 font-semibold"
                      : "text-zinc-400 hover:text-zinc-200"
                  }`}
                >
                  Completion Output
                </button>
                <button
                  onClick={() => setActiveTab("json")}
                  className={`px-3 py-1 rounded-lg transition-all ${
                    activeTab === "json"
                      ? "bg-zinc-800 text-zinc-100 font-semibold"
                      : "text-zinc-400 hover:text-zinc-200"
                  }`}
                >
                  Raw Routing JSON
                </button>
              </div>

              {activeTab === "json" && (
                <button
                  onClick={copyJson}
                  className="flex items-center gap-1.5 px-2 py-1 rounded bg-zinc-800 hover:bg-zinc-700 text-zinc-300 text-[11px]"
                >
                  {copied ? <Check className="h-3 w-3 text-emerald-400" /> : <Copy className="h-3 w-3" />}
                  <span>{copied ? "Copied" : "Copy"}</span>
                </button>
              )}
            </div>

            <div className="mt-3 min-h-[180px]">
              {activeTab === "response" ? (
                <div className="font-mono text-xs text-zinc-300 leading-relaxed whitespace-pre-wrap p-3 rounded-xl bg-zinc-950 border border-zinc-800/80">
                  {simulatedResponse}
                </div>
              ) : (
                <pre className="p-3 rounded-xl bg-zinc-950 border border-zinc-800/80 text-[11px] font-mono text-[#00f0ff] overflow-x-auto max-h-72">
                  {JSON.stringify(decision, null, 2)}
                </pre>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
